import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home () {
  return (
    <div className='w-screen h-screen text-black dark:text-white bg-white dark:bg-black'>
      <Head>
        <title>Utils</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full h-full flex flex-col justify-center items-center'>
        <h1 className='text-4xl mb-12'>
          鱼肚的工具箱
        </h1>
        <ul className='flex flex-col'>
          <li className='cursor-pointer underline'><Link href='/wordle'>Wordle 解题助手</Link></li>
        </ul>
      </main>

      <footer className=''>
      </footer>
    </div>
  )
}
