import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home () {
  const apps = [
    { name: 'Wordle 解题助手', pathname: '/wordle', cover: 'https://banyudu.github.io/images/wordle.png' },
    { name: '镜子', pathname: '/mirror', cover: 'https://banyudu.github.io/images/20221127205403.png' },
    { name: '身份证生成器', pathname: '/id-generator', cover: 'https://banyudu.github.io/images/id_generated.png' },
  ]
  return (
    <div className='w-screen h-screen text-black dark:text-white bg-white dark:bg-black'>
      <Head>
        <title>Utils</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full h-full flex justify-center items-center'>
        <article className='flex flex-col h-72'>
          <h1 className='text-4xl mb-12'>
            鱼肚的工具箱
          </h1>
          <ul className='flex flex-row'>
            {apps.map(app => (
              <li key={app.pathname} className='cursor-pointer underline mb-2 w-48'>
                <Link href={app.pathname}>
                  <div className='flex flex-col'>
                    <img src={app.cover} alt="app cover" className='w-36 h-24 object-cover' width={96} />
                    <span className='mt-4'>{app.name}</span>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        </article>
      </main>

      <footer className=''>
      </footer>
    </div>
  )
}
